stages:
- deploy
- restart
- test
- save_commit
- rollback

before_script: 
- rm -f /tmp/privkey
- echo "$SSH_PRIVATE_KEY" > /tmp/privkey
- chmod 400 /tmp/privkey

push_to_server:
    stage: deploy
    script:
    - ssh -o StrictHostKeyChecking=no -i /tmp/privkey csse@433-21.csse.rose-hulman.edu -t "cd 433-CourseReg && git pull"
    tags: 
    - ubuntu
    
restart_server:
    stage: restart
    script: 
    - ssh -o StrictHostKeyChecking=no -i /tmp/privkey csse@433-21.csse.rose-hulman.edu -t "restartFlaskService"
    tags: 
    - ubuntu
    
run_tests:
    stage: test
    script:
    - chmod +x testing/flaskTests.sh
    - ./testing/flaskTests.sh
    - python3 testing/backendTests.py
    when: on_success
    tags: 
    - ubuntu
    - python
    - csse477

save_good_commit_hash:
    stage: save_commit
    script: 
    - ssh -o StrictHostKeyChecking=no -i /tmp/privkey csse@433-21.csse.rose-hulman.edu -t "echo ${CI_COMMIT_SHA} > lastWorkingCommit"
    when: on_success
    tags: 
    - ubuntu
    
rollback_to_prev:
    stage: rollback
    script:
    - ssh -o StrictHostKeyChecking=no -i /tmp/privkey csse@433-21.csse.rose-hulman.edu -t "revertFlask && restartFlaskService"
    when: on_failure
    tags: 
    - ubuntu
