stages:
- deploy
- restart
- test

before_script: 
- rm -f /tmp/privkey
- echo "$SSH_PRIVATE_KEY" > /tmp/privkey
- chmod 400 /tmp/privkey

push_to_server:
    stage: deploy
    script:
    - ssh -o StrictHostKeyChecking=no -i /tmp/privkey csse@433-21.csse.rose-hulman.edu -t "cd 433-CourseReg && git pull"
    
restart_server:
    stage: restart
    script: 
    - echo "temporarily disabled" # (sleep 3 && echo "exiting" && exit 0) & nohup ssh -o StrictHostKeyChecking=no -i /tmp/privkey csse@433-21.csse.rose-hulman.edu -t "nohup ./restartFlask.sh"
    
run_tests:
    stage: test
    script:
    - chmod +x testing/flaskTests.sh
    - ./testing/flaskTests.sh